### ISSUE TITLE
localhost frontend to remote backend not setting locale cookie

### ISSUE THREAD

**Issue by DashBarkHuss** [WishTender/backend#36]
In the  environment where the local frontend is connected to the remote backend, the front and backends are on different domains: **localhost** and **wishtender**. So cookies sent from wishtender.com cannot be set on localhost:3000. That is how cookies work, they have to be the same domain, but different subdomains are ok.

So in this environment they are set on wishtender.com not localhost:3000. So we can't access the cookies on localhost:3000 (the frontend) in javascript. But we need to access the `locale` cookie in the javascript of the frontend. Since we can't access the `locale` cookie we get this error: 
   >Unexpected token u in JSON at position 0 App.js 52
   
   In all other environments the domains are the same (staging.**wishtender**.com -> api**wishtender**.com, **localhost**:3000=>**localhost**:4000, **localhost** proxy), so we don't have this issue.
   
 But the **localhost**:3000=>api.**wishtender**.com environment is important for frontend devs who don't want to deal with the complexity of setting up a local backend. And in this environment, the frontend needs to access the `locale` cookie just like the other environments. So this must be a situation others have dealt with.
   
   Recreate:
   1. clear cookies in the browser
   2. run the frontend `npm start` which connects to the remote backend server (api.wishtender.com)
   3. navigate to localhost:3000
   4. the browser console will display `Unexpected token u in JSON at position 0 App.js 52`
   
   Does anyone have suggestions?

**Comment by corlaez** [comment]
https://setapp.com/how-to/edit-mac-hosts-file

Editing the hosts file should solve that pesky problem. map your localhost to your deployed subdomain (something like local.wishtender.com)

**Comment by DashBarkHuss** [comment]
Thanks @corlaez, I hadn't realized you could use proxies for localhost to remote, I only thought it was used for connecting between localhost ports. I used the proxy idea. Now, on the front end if you want to connect to the remote server from localhost, you run `npm run proxytoremote` [front end pull request](https://github.com/WishTender/frontend/pull/35). Now, `npm run proxytoremote` should be what frontend devs use to start the app, if they do not have the backend locally.

**Comment by DashBarkHuss** [comment]
The proxy doesn't seem to be working on safari.
1. `npm run proxytoremote` on frontend
2. navigate to home page
   gives an error:
   > Unhandled Rejection (SyntaxError): JSON Parse error: Unexpected identifier "undefined"
(anonymous function)
src/App.js:52

   this is because the `locale` cookie is undefined. Neither the `locale` or `connect.sid` (session cookie) are being set. There are set-cookie headers but it's not doing anything: 
   >Set-Cookie: locale=%7B%22locale%22%3A%22en-us%22%2C%22countryCode%22%3A%22US%22%2C%22languageCode%22%3A%22en%22%7D; Max-Age=1618456; Path=/; Expires=Mon, 03 May 2021 20:39:43 GMT; Secure; SameSite=None
    >Set-Cookie: connect.sid=s%3ABCDOhGNwluOVGKsBNU8QWNTh_yyOJaFQ.KjgaCSkaVZ5gZfSxd51u%2FjWsd%2FMLNvPdJBbbHs%2Bpoik; Path=/; HttpOnly; Secure; SameSite=None

**Comment by DashBarkHuss** [comment]
seems unrelated to the proxy because now I'm seeing the same problem on the local environments on safari.
